<?php
/**
 * @file
 * Provides publish to ftp feature for homepages.
 */

/**
 * Implements hook_help().
 */
function wget_static_help($path, $arg) {
  switch ($path) {
    case 'admin/help#wget_static':
      $output = file_get_contents(drupal_get_path('module', 'wget_static') . '/README.txt');
      return $output;
  }
}

/**
 * Implements hook_cron().
 */
function wget_static_cron() {
  // Deleting temporary files.
  file_unmanaged_delete_recursive(file_directory_temp() . '/wget');
  file_unmanaged_delete(file_directory_temp() . '/wget.log');
}
